{"name": "Проверка сообщения: Неверная учетная запись или пароль при неуспешной авторизации с неверным паролем", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: None\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:305:16", "trace": "self = <pages.LoginPage.CheckLogin object at 0x0000018750E55210>, locator = ('class name', 'mb-3Q'), time = 2\n\n    def find_element(self, locator, time=2):\n        try:\n>           return WebDriverWait(self.driver, time).until(expected_conditions.presence_of_element_located(locator))\n\n..\\pages\\BaseApp.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"d9ca3495-bdc0-4f07-9cf9-5eaea8fe9b5e\")>, method = <function presence_of_element_located.<locals>._predicate at 0x0000018750E68EE0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nE       element.find/</<@chrome://remote/content/marionette/element.js:305:16\n\n..\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nbrowser = <selenium.webdriver.remote.webdriver.WebDriver (session=\"d9ca3495-bdc0-4f07-9cf9-5eaea8fe9b5e\")>, login = 'admin', password = '0000'\n\n    @allure.title('Проверка сообщения: Неверная учетная запись или пароль при неуспешной авторизации с неверным паролем')\n    @allure.severity(allure.severity_level.MINOR)\n    @pytest.mark.parametrize('login, password', [('admin', '0000')])\n    def test_wrong_password(browser, login, password):\n        login_page = ActionLogin(browser)\n        login_page.go_to_site()\n        login_page.enter_login_and_password(login, password)\n        login_page = CheckLogin(browser)\n>       message = login_page.check_wrong_login_message()\n\ntest_autorization.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\LoginPage.py:30: in check_wrong_login_message\n    wrong_login_message = self.find_element(SearchLocators.wrong_login_message)\n..\\pages\\BaseApp.py:16: in find_element\n    return WebDriverWait(self.driver, time).until(expected_conditions.presence_of_element_located(locator), allure.attach(self.driver.get_screenshot_as_png(), name=f\"{locator} NOT FOUND\", attachment_type=AttachmentType.PNG))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"d9ca3495-bdc0-4f07-9cf9-5eaea8fe9b5e\")>, method = <function presence_of_element_located.<locals>._predicate at 0x0000018750E69000>, message = None\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: None\nE       Stacktrace:\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nE       element.find/</<@chrome://remote/content/marionette/element.js:305:16\n\n..\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "attachments": [{"name": "('class name', 'mb-3Q') NOT FOUND", "source": "89e34c28-ec34-48ff-8140-d54dffdf5eba-attachment.png", "type": "image/png"}], "parameters": [{"name": "login", "value": "'admin'"}, {"name": "password", "value": "'0000'"}], "start": 1654212590387, "stop": 1654212597369, "uuid": "d5898d28-2e5e-43c7-b3b8-56aafca2ec55", "historyId": "6aa3aea12b4545c80de0ee9822b6c4e1", "testCaseId": "54480efe2e4ff410ebfbe4100261b9b8", "fullName": "test_autorization#test_wrong_password", "labels": [{"name": "severity", "value": "minor"}, {"name": "suite", "value": "test_autorization"}, {"name": "host", "value": "DESKTOP-13RCMAF"}, {"name": "thread", "value": "38248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_autorization"}]}